[package]
name = "errors"
version = "0.1.0"
authors = ["Vincent Prouillet <prouillet.vincent@gmail.com>"]

[dependencies]
error-chain = "0.12"
tera = { git = "https://github.com/Keats/tera/", branch = "next" }
toml = "0.4"
image = "0.20"
