[package]
name = "gutenberg"
version = "0.1.0"
authors = ["Vincent Prouillet <vincent@wearewizards.io>"]
license = "MIT"
readme = "README.md"
description = "Static site generator"
homepage = "https://github.com/Keats/gutenberg"
repository = "https://github.com/Keats/gutenberg"
keywords = ["static", "site", "generator", "blog"]

[dependencies]
error-chain = "0.10"
clap = "2.19"
walkdir = "1"
pulldown-cmark = "0"
regex = "0.2"
lazy_static = "0.2"
glob = "0.2"
serde = "0.9"
serde_json = "0.9"
serde_derive = "0.9"
tera = { git = "https://github.com/Keats/tera", branch = "master" }
# tera = "0.8"
slug = "0.1"
syntect = "1"
chrono = "0.3"

# Below is for the serve cmd
staticfile = "0.4"
iron = "0.5"
mount = "0.3"
notify = "4"
ws = "0.6"

[dependencies.toml]
version = "0.3"
default-features = false
features = ["serde"]


