[package]
name = "gutenberg"
version = "0.1.0"
authors = ["Vincent Prouillet <vincent@wearewizards.io>"]
license = "MIT"
readme = "README.md"
description = "Static site generator"
homepage = "https://github.com/Keats/gutenberg"
repository = "https://github.com/Keats/gutenberg"
keywords = ["static", "site", "generator", "blog"]

[dependencies]
error-chain = "0.7"
clap = "2.19"
walkdir = "1"
pulldown-cmark = "0"
regex = "0.1"
lazy_static = "0.2"
glob = "0.2"
serde = "0.8"
serde_json = "0.8"
serde_derive = "0.8"
tera = "0.5"

[dependencies.toml]
version = "0.2"
default-features = false
features = ["serde"]


