[package]
name = "config"
version = "0.1.0"
authors = ["Vincent Prouillet <vincent@wearewizards.io>"]

[dependencies]
toml = "0.4"
serde = "1"
serde_derive = "1"
chrono = "0.4"

errors = { path = "../errors" }
highlighting = { path = "../highlighting"}
