[package]
name = "utils"
version = "0.1.0"
authors = ["Vincent Prouillet <vincent@wearewizards.io>"]

[dependencies]
errors = { path = "../errors" }
tera = "0.10"


[dev-dependencies]
tempdir = "0.3"
