[package]
name = "imageproc"
version = "0.1.0"
authors = ["Vojtěch Král <vojtech@kral.hk>"]

[dependencies]
lazy_static = "1"
regex = "1.0"
tera = { git = "https://github.com/Keats/tera/", branch = "next" }
image = "0.20"
rayon = "1"

errors = { path = "../errors" }
utils = { path = "../utils" }
